### PR TITLE
Responsive version (#25)

### PR DESCRIPTION
**Pull request by almirfilho**
Responsive version (ok on mobile) among other few improvements.

### CODE REVIEW

**Comment by andrewsmedina** [comment]
@almirfilho thanks! can you remove the ".editorconfig" ? and  can you change the burger menu color to #fff and #3d9 hover ?

**Comment by almirfilho** [comment]
@andrewsmedina done!

**Comment by andrewsmedina** [comment]
@almirfilho thank you! \o/

**Comment by tarsisazevedo** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap:

**Pull request merged**
